import type { App } from 'vue';
import ElAffix from './mf-affix';
import ElAlert from './mf-alert';
import ElAside from './mf-aside';
import ElAutocomplete from './mf-autocomplete';
import ElAvatar from './mf-avatar';
import ElBacktop from './mf-backtop';
import ElBadge from './mf-badge';
import ElBreadcrumb from './mf-breadcrumb';
import ElBreadcrumbItem from './mf-breadcrumb-item';
import ElButton from './mf-button';
import ElButtonGroup from './mf-button-group';
import ElCalendar from './mf-calendar';
import ElCard from './mf-card';
import ElCarousel from './mf-carousel';
import ElCarouselItem from './mf-carousel-item';
import ElCascader from './mf-cascader';
import ElCascaderPanel from './mf-cascader-panel';
import ElCheckbox from './mf-checkbox';
import ElCheckboxButton from './mf-checkbox-button';
import ElCheckboxGroup from './mf-checkbox-group';
import ElCol from './mf-col';
import ElCollapse from './mf-collapse';
import ElCollapseItem from './mf-collapse-item';
import ElCollapseTransition from './mf-collapse-transition';
import ElColorPicker from './mf-color-picker';
import ElContainer from './mf-container';
import ElDatePicker from './mf-date-picker';
import ElDialog from './mf-dialog';
import ElDivider from './mf-divider';
import ElDrawer from './mf-drawer';
import ElDropdown from './mf-dropdown';
import ElDropdownItem from './mf-dropdown-item';
import ElDropdownMenu from './mf-dropdown-menu';
import ElEmpty from './mf-empty';
import ElFooter from './mf-footer';
import ElForm from './mf-form';
import ElFormItem from './mf-form-item';
import ElHeader from './mf-header';
import ElIcon from './mf-icon';
import ElImage from './mf-image';
import ElImageViewer from './mf-image-viewer';
import ElInfiniteScroll from './mf-infinite-scroll';
import ElInput from './mf-input';
import ElInputNumber from './mf-input-number';
import ElLink from './mf-link';
import ElLoading from './mf-loading';
import ElMain from './mf-main';
import ElMenu from './mf-menu';
import ElMenuItem from './mf-menu-item';
import ElMenuItemGroup from './mf-menu-item-group';
import ElMessage from './mf-message';
import ElMessageBox from './mf-message-box';
import ElNotification from './mf-notification';
import ElOption from './mf-option';
import ElOptionGroup from './mf-option-group';
import ElPageHeader from './mf-page-header';
import ElPagination from './mf-pagination';
import ElPopconfirm from './mf-popconfirm';
import ElPopover from './mf-popover';
import ElPopper from './mf-popper';
import ElProgress from './mf-progress';
import ElRadio from './mf-radio';
import ElRadioButton from './mf-radio-button';
import ElRadioGroup from './mf-radio-group';
import ElRate from './mf-rate';
import ElRow from './mf-row';
import ElScrollbar from './mf-scrollbar';
import ElSelect from './mf-select';
import ElSlider from './mf-slider';
import ElStep from './mf-step';
import ElSteps from './mf-steps';
import ElSubmenu from './mf-submenu';
import ElSwitch from './mf-switch';
import ElTabPane from './mf-tab-pane';
import ElTable from './mf-table';
import ElTableColumn from './mf-table-column';
import ElTabs from './mf-tabs';
import ElTag from './mf-tag';
import ElTimePicker from './mf-time-picker';
import ElTimeSelect from './mf-time-select';
import ElTimeline from './mf-timeline';
import ElTimelineItem from './mf-timeline-item';
import ElTooltip from './mf-tooltip';
import ElTransfer from './mf-transfer';
import ElTree from './mf-tree';
import ElUpload from './mf-upload';
import ElSpace from './mf-space';
import ElSkeleton from './mf-skeleton';
import ElSkeletonItem from './mf-skeleton-item';
import ElCheckTag from './mf-check-tag';
import ElDescriptions from './mf-descriptions';
import ElDescriptionsItem from './mf-descriptions-item';
import ElResult from './mf-result';
import ElSelectV2 from './mf-select-v2';
import type { InstallOptions } from './mf-utils/config';
declare const version = "0.0.0-development";
declare const locale: (l: import("./mf-locale").Language) => void;
declare const install: (app: App, opt: InstallOptions) => void;
export { ElAffix, ElAlert, ElAside, ElAutocomplete, ElAvatar, ElBacktop, ElBadge, ElBreadcrumb, ElBreadcrumbItem, ElButton, ElButtonGroup, ElCalendar, ElCard, ElCarousel, ElCarouselItem, ElCascader, ElCascaderPanel, ElCheckbox, ElCheckboxButton, ElCheckboxGroup, ElCheckTag, ElCol, ElCollapse, ElCollapseItem, ElCollapseTransition, ElColorPicker, ElContainer, ElDatePicker, ElDialog, ElDivider, ElDrawer, ElDropdown, ElDropdownItem, ElDropdownMenu, ElEmpty, ElFooter, ElForm, ElFormItem, ElHeader, ElIcon, ElImage, ElImageViewer, ElInfiniteScroll, ElInput, ElInputNumber, ElLink, ElLoading, ElMain, ElMenu, ElMenuItem, ElMenuItemGroup, ElMessage, ElMessageBox, ElNotification, ElOption, ElOptionGroup, ElPageHeader, ElPagination, ElPopconfirm, ElPopover, ElPopper, ElProgress, ElRadio, ElRadioButton, ElRadioGroup, ElRate, ElRow, ElScrollbar, ElSelect, ElSlider, ElStep, ElSteps, ElSubmenu, ElSwitch, ElTabPane, ElTable, ElTableColumn, ElTabs, ElTag, ElTimePicker, ElTimeSelect, ElTimeline, ElTimelineItem, ElTooltip, ElTransfer, ElTree, ElUpload, ElSpace, ElSkeleton, ElSkeletonItem, ElDescriptions, ElDescriptionsItem, ElResult, ElSelectV2, version, install, locale, };
declare const _default: {
    version: string;
    install: (app: App<any>, opt: InstallOptions) => void;
};
export default _default;
